Metrics/AbcSize:
  Max: 378

Metrics/BlockLength:
  Max: 186

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 1200

Metrics/MethodLength:
  Max: 90

Metrics/PerceivedComplexity:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 30

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 130
