Bundler/DuplicatedGem:
  Exclude:
    - "Gemfile"

Bundler/DuplicatedGroup:
  Exclude:
    - "Gemfile"

Metrics/AbcSize:
  Max: 278

Metrics/BlockLength:
  Max: 186

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 1200

Metrics/MethodLength:
  Max: 67

Metrics/PerceivedComplexity:
  Max: 14

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 130
